const RUDRAM_DATA = {
  "namakam": [
    {
      "number": 1,
      "section": "namakam",
      "sanskrit": "ॐ नमो भगवते रुद्राय ॥\nॐ नमस्ते रुद्र मन्यव उतो त इषवे नमः । नमस्ते अस्तु धन्वने बाहुभ्यामुत ते नमः ॥\nया त इषुः शिवतमा शिवं बभूव ते धनुः । शिवा शरव्या या तव तया नो रुद्र मृडय ॥\nया ते रुद्र शिवा तनूरघोराऽपापकाशिनी । तया नस्तनुवा शन्तमया गिरिशन्ताभिचाकशीहि ॥\nयामिषुं गिरिशन्त हस्ते बिभर्ष्यस्तवे । शिवां गिरित्र तां कुरु मा हिꣳसीः पुरुषं जगत् ॥\nशिवेन वचसा त्वा गिरिशाच्छावदामसि । यथा नः सर्वमिज्जगदयक्ष्मꣳ सुमना असत् ॥\nअध्यवोचदधिवक्ता प्रथमो दैव्यो भिषक् । अहीꣳश्च सर्वाञ्जम्भयन्त्सर्वाश्च यातुधान्यः ॥\nअसौ यस्ताम्रो अरुण उत बभ्रुः सुमङ्गलः । ये चेमाꣳ रुद्रा अभितो दिक्षु श्रिताः सहस्रशोऽवैषाꣳ हेड ईमहे ॥\nअसौ योऽवसर्पति नीलग्रीवो विलोहितः । उतैनं गोपा अदृश्रन्नदृश्रन्नुदहार्यः । उतैनं विश्वा भूतानि स दृष्टो मृडयाति नः ॥\nनमो अस्तु नीलग्रीवाय सहस्राक्षाय मीढुषे । अथो ये अस्य सत्वानोऽहं तेभ्योऽकरन्नमः ॥\nप्रमुञ्च धन्वनस्त्वमुभयोरार्त्नियोर्ज्याम् । याश्च ते हस्त इषवः परा ता भगवो वप ॥\nअवतत्य धनुस्त्वꣳ सहस्राक्ष शतेषुधे । निशीर्य शल्यानां मुखा शिवो नः सुमना भव ॥\nविज्यं धनुः कपर्दिनो विशल्यो बाणवाꣳ उत । अनेशन्नस्येषव आभुरस्य निषङ्गथिः ॥\nया ते हेतिर्मीढुष्टम हस्ते बभूव ते धनुः । तयाऽस्मान् विश्वतस्त्वमयक्ष्मया परिब्भुज ॥\nनमस्ते अस्त्वायुधायानातताय धृष्णवे । उभाभ्यामुत ते नमो बाहुभ्यां तव धन्वने ॥\nपरि ते धन्वनो हेतिरस्मान्वृणक्तु विश्वतः । अथो य इषुधिस्तवारे अस्मन्निधेहि तम् ॥ १ ॥",
      "transliteration": "oṃ namo bhagavate rudrāya ||\noṃ namaste rudra manyava uto ta iṣave namaḥ | namaste astu dhanvane bāhubhyāmuta te namaḥ ||\nyā ta iṣuḥ śivatamā śivaṃ babhūva te dhanuḥ | śivā śaravyā yā tava tayā no rudra mṛḍaya ||\nyā te rudra śivā tanūraghorā'pāpakāśinī | tayā nastanuvā śantamayā giriśantābhicākaśīhi ||\nyāmiṣuṃ giriśanta haste bibharṣyastave | śivāṃ giritra tāṃ kuru mā hiṃsīḥ puruṣaṃ jagat ||\nśivena vacasā tvā giriśācchāvadāmasi | yathā naḥ sarvamijjagadayakṣmaṃ sumanā asat ||\nadhyavocadadhivaktā prathamo daivyo bhiṣak | ahīṃśca sarvāñjambhayantsarvāśca yātudhānyaḥ ||\nasau yastāmro aruṇa uta babhruḥ sumaṅgalaḥ | ye cemāṃ rudrā abhito dikṣu śritāḥ sahasraśo'vaiṣāṃ heḍa īmahe ||\nasau yo'vasarpati nīlagrīvo vilohitaḥ | utainaṃ gopā adṛśrannadṛśrannudahāryaḥ | utainaṃ viśvā bhūtāni sa dṛṣṭo mṛḍayāti naḥ ||\nnamo astu nīlagrīvāya sahasrākṣāya mīḍhuṣe | atho ye asya satvāno'haṃ tebhyo'karannamaḥ ||\npramuñca dhanvanastvamubhayorārtniyorjyām | yāśca te hasta iṣavaḥ parā tā bhagavo vapa ||\navatatya dhanustvaṃ sahasrākṣa śateṣudhe | niśīrya śalyānāṃ mukhā śivo naḥ sumanā bhava ||\nvijyaṃ dhanuḥ kapardino viśalyo bāṇavāṃ uta | aneśannasyeṣava ābhurasya niṣaṅgathiḥ ||\nyā te hetirmīḍhuṣṭama haste babhūva te dhanuḥ | tayā'smān viśvatastvamayakṣmayā paribbhuja ||\nnamaste astvāyudhāyānātatāya dhṛṣṇave | ubhābhyāmuta te namo bāhubhyāṃ tava dhanvane ||\npari te dhanvano hetirasmānvṛṇaktu viśvataḥ | atho ya iṣudhistavāre asmannidhehi tam || 1 ||",
      "theme": "Salutations to Rudra's wrath and weapons",
      "meaning": "The opening anuvaka offers salutations to Rudra's anger, His arrows, His bow, and His mighty arms, praying that He lay down His weapons and show His auspicious (shiva) form. The seeker invokes Rudra as the first divine physician who destroys all diseases and evil forces, requesting Him to turn His destructive aspects away and bless with His benevolent, sin-free form (aghora apapakashini tanu). It culminates in the famous prayer for Rudra to unstring His bow and place His quiver far from us.",
      "youtubeTime": 4
    },
    {
      "number": 2,
      "section": "namakam",
      "sanskrit": "नमो हिरण्यबाहवे सेनान्ये दिशां च पतये नमो नमो वृक्षेभ्यो हरिकेशेभ्यः पशूनां पतये नमो नमः सस्पिञ्जराय त्विषीमते पथीनां पतये नमो नमो बभ्लुशाय विव्याधिनेऽन्नानां पतये नमो नमो हरिकेशायोपवीतिने पुष्टानां पतये नमो नमो भवस्य हेत्यै जगतां पतये नमो नमो रुद्रायातताविने क्षेत्राणां पतये नमो नमः सूतायाहन्त्याय वनानां पतये नमो नमो रोहिताय स्थपतये वृक्षाणां पतये नमो नमो मन्त्रिणे वाणिजाय कक्षाणां पतये नमो नमो भुवन्तये वारिवस्कृतायौषधीनां पतये नमो नम उच्चैर्घोषायाक्रन्दयते पत्तीनां पतये नमो नमः कृत्स्नवीताय धावते सत्त्वनां पतये नमः ॥ २ ॥",
      "transliteration": "namo hiraṇyabāhave senānye diśāṃ ca pataye namo namo vṛkṣebhyo harikeśebhyaḥ paśūnāṃ pataye namo namaḥ saspiñjarāya tviṣīmate pathīnāṃ pataye namo namo babhluśāya vivyādhine'nnānāṃ pataye namo namo harikeśāyopavītine puṣṭānāṃ pataye namo namo bhavasya hetyai jagatāṃ pataye namo namo rudrāyātatāvine kṣetrāṇāṃ pataye namo namaḥ sūtāyāhantyāya vanānāṃ pataye namo namo rohitāya sthapataye vṛkṣāṇāṃ pataye namo namo mantriṇe vāṇijāya kakṣāṇāṃ pataye namo namo bhuvantaye vārivaskṛtāyauṣadhīnāṃ pataye namo nama uccairghoṣāyākrandayate pattīnāṃ pataye namo namaḥ kṛtsnavītāya dhāvate sattvanāṃ pataye namaḥ || 2 ||",
      "theme": "Salutations to Rudra as cosmic leader and lord of beings",
      "meaning": "This anuvaka salutes Rudra as the golden-armed chief of cosmic armies, lord of directions, and master of all trees, animals, roads, food, and pathways. He is praised as the one with flowing green hair who wears the sacred thread, the lord of fields, forests, medicinal herbs, and warriors. Each epithet reveals Rudra's pervasive presence as the protector and ruler of every sphere of existence, from the material world of commerce to the wild forests and growing plants.",
      "youtubeTime": 173
    },
    {
      "number": 3,
      "section": "namakam",
      "sanskrit": "नमः सहमानाय निव्याधिन आव्याधिनीनां पतये नमो नमः ककुभाय निषङ्गिणे स्तेनानां पतये नमो नमो निषङ्गिण इषुधिमते तस्कराणां पतये नमो नमो वञ्चते परिवञ्चते स्तायूनां पतये नमो नमो निचेरवे परिचरायारण्यानां पतये नमो नमः सृकाविभ्यो जिघाꣳसद्भ्यो मुष्णतां पतये नमो नमोऽसिमद्भ्यो नक्तञ्चरद्भ्यः प्रकृन्तानां पतये नमो नम उष्णीषिणे गिरिचराय कुलुञ्चानां पतये नमो नम इषुमद्भ्यो धन्वाविभ्यश्च वो नमो नम आतन्वानेभ्यः प्रतिदधानेभ्यश्च वो नमो नम आयच्छद्भ्यो विसृजद्भ्यश्च वो नमो नमोऽस्यद्भ्यो विद्ध्यद्भ्यश्च वो नमो नम आसीनेभ्यः शयानेभ्यश्च वो नमो नमः स्वपद्भ्यो जाग्रद्भ्यश्च वो नमो नमस्तिष्ठद्भ्यो धावद्भ्यश्च वो नमो नमः सभाभ्यः सभापतिभ्यश्च वो नमो नमो अश्वेभ्योऽश्वपतिभ्यश्च वो नमः ॥ ३ ॥",
      "transliteration": "namaḥ sahamānāya nivyādhina āvyādhinīnāṃ pataye namo namaḥ kakubhāya niṣaṅgiṇe stenānāṃ pataye namo namo niṣaṅgiṇa iṣudhimate taskarāṇāṃ pataye namo namo vañcate parivañcate stāyūnāṃ pataye namo namo nicerave paricarāyāraṇyānāṃ pataye namo namaḥ sṛkāvibhyo jighāṃsadbhyo muṣṇatāṃ pataye namo namo'simadbhyo naktañcaradbhyaḥ prakṛntānāṃ pataye namo nama uṣṇīṣiṇe giricarāya kuluñcānāṃ pataye namo nama iṣumadbhyo dhanvāvibhyaśca vo namo nama ātanvānebhyaḥ pratidadhānebhyaśca vo namo nama āyacchadbhyo visṛjadbhyaśca vo namo namo'syadbhyo viddhyadbhyaśca vo namo nama āsīnebhyaḥ śayānebhyaśca vo namo namaḥ svapadbhyo jāgradbhyaśca vo namo namastiṣṭhadbhyo dhāvadbhyaśca vo namo namaḥ sabhābhyaḥ sabhāpatibhyaśca vo namo namo aśvebhyo'śvapatibhyaśca vo namaḥ || 3 ||",
      "theme": "Salutations to Rudra as conqueror in all forms",
      "meaning": "This anuvaka recognizes that Rudra dwells even in those we perceive as adversaries - thieves, robbers, cheats, and nighttime marauders. He is saluted as the conqueror, the tall one with his quiver, the lord of mountain dwellers and forest rangers. The salutations extend to all who hold arrows and bows, who shoot and strike, who sit and lie, who sleep and wake, who stand and run, showing that every action and every being is ultimately a manifestation of Rudra.",
      "youtubeTime": 231
    },
    {
      "number": 4,
      "section": "namakam",
      "sanskrit": "नम आव्याधिनीभ्यो विविध्यन्तीभ्यश्च वो नमो नम उगणाभ्यस्तृꣳहतीभ्यश्च वो नमो नमो गृत्सेभ्यो गृत्सपतिभ्यश्च वो नमो नमो व्रातेभ्यो व्रातपतिभ्यश्च वो नमो नमो गणेभ्यो गणपतिभ्यश्च वो नमो नमो विरूपेभ्यो विश्वरूपेभ्यश्च वो नमो नमो महद्भ्यः क्षुल्लकेभ्यश्च वो नमो नमो रथिभ्योऽरथेभ्यश्च वो नमो नमो रथेभ्यो रथपतिभ्यश्च वो नमो नमः सेनाभ्यः सेनानिभ्यश्च वो नमो नमः क्षत्तृभ्यः सङ्ग्रहीतृभ्यश्च वो नमो नमस्तक्षभ्यो रथकारेभ्यश्च वो नमो नमः कुलालेभ्यः कर्मारेभ्यश्च वो नमो नमः पुञ्जिष्टेभ्यो निषादेभ्यश्च वो नमो नम इषुकृद्भ्यो धन्वकृद्भ्यश्च वो नमो नमो मृगयुभ्यः श्वनिभ्यश्च वो नमो नमः श्वभ्यः श्वपतिभ्यश्च वो नमः ॥ ४ ॥",
      "transliteration": "nama āvyādhinībhyo vividhyantībhyaśca vo namo nama ugaṇābhyastṛṃhatībhyaśca vo namo namo gṛtsebhyo gṛtsapatibhyaśca vo namo namo vrātebhyo vrātapatibhyaśca vo namo namo gaṇebhyo gaṇapatibhyaśca vo namo namo virūpebhyo viśvarūpebhyaśca vo namo namo mahadbhyaḥ kṣullakebhyaśca vo namo namo rathibhyo'rathebhyaśca vo namo namo rathebhyo rathapatibhyaśca vo namo namaḥ senābhyaḥ senānibhyaśca vo namo namaḥ kṣattṛbhyaḥ saṅgrahītṛbhyaśca vo namo namastakṣabhyo rathakārebhyaśca vo namo namaḥ kulālebhyaḥ karmārebhyaśca vo namo namaḥ puñjiṣṭebhyo niṣādebhyaśca vo namo nama iṣukṛdbhyo dhanvakṛdbhyaśca vo namo namo mṛgayubhyaḥ śvanibhyaśca vo namo namaḥ śvabhyaḥ śvapatibhyaśca vo namaḥ || 4 ||",
      "theme": "Salutations to Rudra in all occupations and forms",
      "meaning": "This anuvaka honors Rudra dwelling in every occupation and social role - carpenters, chariot-makers, potters, blacksmiths, fishermen, hunters, and arrow-makers. He is saluted in leaders of troops (Ganapati, Vratapati), in the great and the small, in those of odd and universal forms, in charioteers and foot soldiers. The all-inclusive nature of these salutations affirms that no vocation or station in life is outside Rudra's divine presence.",
      "youtubeTime": 302
    },
    {
      "number": 5,
      "section": "namakam",
      "sanskrit": "नमो भवाय च रुद्राय च नमः शर्वाय च पशुपतये च नमो नीलग्रीवाय च शितिकण्ठाय च नमः कपर्दिने च व्युप्तकेशाय च नमः सहस्राक्षाय च शतधन्वने च नमो गिरिशयाय च शिपिविष्टाय च नमो मीढुष्टमाय चेषुमते च नमो ह्रस्वाय च वामनाय च नमो बृहते च वर्षीयसे च नमो वृद्धाय च सꣳवृध्वने च नमो अग्रियाय च प्रथमाय च नम आशवे चाजिराय च नमः शीघ्रियाय च शीभ्याय च नम ऊर्म्याय चावस्वन्याय च नमः स्रोतस्याय च द्वीप्याय च ॥ ५ ॥",
      "transliteration": "namo bhavāya ca rudrāya ca namaḥ śarvāya ca paśupataye ca namo nīlagrīvāya ca śitikaṇṭhāya ca namaḥ kapardine ca vyuptakeśāya ca namaḥ sahasrākṣāya ca śatadhanvane ca namo giriśayāya ca śipiviṣṭāya ca namo mīḍhuṣṭamāya ceṣumate ca namo hrasvāya ca vāmanāya ca namo bṛhate ca varṣīyase ca namo vṛddhāya ca saṃvṛdhvane ca namo agriyāya ca prathamāya ca nama āśave cājirāya ca namaḥ śīghriyāya ca śībhyāya ca nama ūrmyāya cāvasvanyāya ca namaḥ srotasyāya ca dvīpyāya ca || 5 ||",
      "theme": "Salutations to Rudra in cosmic forms and dimensions",
      "meaning": "This anuvaka salutes Rudra by His primary cosmic names - Bhava (existence), Rudra, Sharva (destroyer), Pashupati (lord of beings), Nilagriva (blue-throated), and Shitikantha (white-throated). He is saluted in forms ranging from short and dwarf to vast and tall, from young and growing to ancient and foremost. He pervades the swift and slow, the waves and currents, the rivers and islands, showing His presence across all dimensions of space and time.",
      "youtubeTime": 364
    },
    {
      "number": 6,
      "section": "namakam",
      "sanskrit": "नमो ज्येष्ठाय च कनिष्ठाय च नमः पूर्वजाय चापरजाय च नमो मध्यमाय चापगल्भाय च नमो जघन्याय च बुध्नियाय च नमः सोभ्याय च प्रतिसर्याय च नमो याम्याय च क्षेम्याय च नम उर्वर्याय च खल्याय च नमः श्लोक्याय चावसान्याय च नमो वन्याय च कक्ष्याय च नमः श्रवाय च प्रतिश्रवाय च नम आशुषेणाय चाशुरथाय च नमः शूराय चावभिन्दते च नमो वर्मिणे च वरूथिने च नमो बिल्मिने च कवचिने च नमः श्रुताय च श्रुतसेनाय च ॥ ६ ॥",
      "transliteration": "namo jyeṣṭhāya ca kaniṣṭhāya ca namaḥ pūrvajāya cāparajāya ca namo madhyamāya cāpagalbhāya ca namo jaghanyāya ca budhniyāya ca namaḥ sobhyāya ca pratisaryāya ca namo yāmyāya ca kṣemyāya ca nama urvaryāya ca khalyāya ca namaḥ ślokyāya cāvasānyāya ca namo vanyāya ca kakṣyāya ca namaḥ śravāya ca pratiśravāya ca nama āśuṣeṇāya cāśurathāya ca namaḥ śūrāya cāvabhindate ca namo varmiṇe ca varūthine ca namo bilmine ca kavacine ca namaḥ śrutāya ca śrutasenāya ca || 6 ||",
      "theme": "Salutations to Rudra across all relativities and states",
      "meaning": "This anuvaka salutes Rudra in every relational dimension - eldest and youngest, firstborn and lastborn, middle and eager, lowest and deepest. He is saluted in the fertile fields and threshing floors, in the forests and thickets, in fame and echo, in the swift-armied and swift-chariot warriors. The hero who cleaves asunder, the one clad in armor and helmet, the renowned one and lord of famous armies - all are Rudra's manifestations.",
      "youtubeTime": 408
    },
    {
      "number": 7,
      "section": "namakam",
      "sanskrit": "नमो दुन्दुभ्याय चाहनन्याय च नमो धृष्णवे च प्रमृशाय च नमो दूताय च प्रहिताय च नमो निषङ्गिणे चेषुधिमते च नमस्तीक्ष्णेषवे चायुधिने च नमः स्वायुधाय च सुधन्वने च नमः स्रुत्याय च पथ्याय च नमः काट्याय च नीप्याय च नमः सूद्याय च सरस्याय च नमो नाद्याय च वैशन्ताय च नमः कूप्याय चावट्याय च नमो वर्ष्याय चावर्ष्याय च नमो मेघ्याय च विद्युत्याय च नम ईध्रियाय चातप्याय च नमो वात्याय च रेष्मियाय च नमो वास्तव्याय च वास्तुपाय च ॥ ७ ॥",
      "transliteration": "namo dundubhyāya cāhananyāya ca namo dhṛṣṇave ca pramṛśāya ca namo dūtāya ca prahitāya ca namo niṣaṅgiṇe ceṣudhimate ca namastīkṣṇeṣave cāyudhine ca namaḥ svāyudhāya ca sudhanvane ca namaḥ srutyāya ca pathyāya ca namaḥ kāṭyāya ca nīpyāya ca namaḥ sūdyāya ca sarasyāya ca namo nādyāya ca vaiśantāya ca namaḥ kūpyāya cāvaṭyāya ca namo varṣyāya cāvarṣyāya ca namo meghyāya ca vidyutyāya ca nama īdhriyāya cātapyāya ca namo vātyāya ca reṣmiyāya ca namo vāstavyāya ca vāstupāya ca || 7 ||",
      "theme": "Salutations to Rudra in nature, weather, and locations",
      "meaning": "This anuvaka salutes Rudra as the drum and its beating, as the bold explorer, as the messenger and the sent. He is praised in the quiver-bearer, sharp-arrow wielder, and well-armed archer. Rudra pervades every natural feature - paths and trenches, wells and ponds, streams and lakes, clouds and lightning, sun and wind, storms and rain. He dwells in dwelling-places and as protector of homes, affirming His presence in every element of nature and habitation.",
      "youtubeTime": 450
    },
    {
      "number": 8,
      "section": "namakam",
      "sanskrit": "नमः सोमाय च रुद्राय च नमस्ताम्राय चारुणाय च नमः शङ्गाय च पशुपतये च नम उग्राय च भीमाय च नमो अग्रेवधाय च दूरेवधाय च नमो हन्त्रे च हनीयसे च नमो वृक्षेभ्यो हरिकेशेभ्यो नमस्ताराय नमः शम्भवे च मयोभवे च नमः शङ्कराय च मयस्कराय च नमः शिवाय च शिवतराय च नमस्तीर्थ्याय च कूल्याय च नमः पार्याय चावार्याय च नमः प्रतरणाय चोत्तरणाय च नम आतार्याय चालाद्याय च नमः शष्प्याय च फेन्याय च नमः सिकत्याय च प्रवाह्याय च ॥ ८ ॥",
      "transliteration": "namaḥ somāya ca rudrāya ca namastāmrāya cāruṇāya ca namaḥ śaṅgāya ca paśupataye ca nama ugrāya ca bhīmāya ca namo agrevadhāya ca dūrevadhāya ca namo hantre ca hanīyase ca namo vṛkṣebhyo harikeśebhyo namastārāya namaḥ śambhave ca mayobhave ca namaḥ śaṅkarāya ca mayaskarāya ca namaḥ śivāya ca śivatarāya ca namastīrthyāya ca kūlyāya ca namaḥ pāryāya cāvāryāya ca namaḥ prataraṇāya cottaraṇāya ca nama ātāryāya cālādyāya ca namaḥ śaṣpyāya ca phenyāya ca namaḥ sikatyāya ca pravāhyāya ca || 8 ||",
      "theme": "Salutations to Rudra as Soma, auspicious and fierce",
      "meaning": "This anuvaka contains the celebrated mantras saluting Rudra as Soma (the cosmic elixir), as copper-colored and ruddy, as Shambhu (source of happiness) and Mayobhava (giver of bliss), as Shankara (maker of peace) and Shiva (the auspicious one), and Shivatara (even more auspicious). He is the fierce and terrible, the slayer near and far, the savior who helps us cross over - residing in pilgrimage sites, riverbanks, fords, and grassy meadows.",
      "youtubeTime": 492
    },
    {
      "number": 9,
      "section": "namakam",
      "sanskrit": "नम इरिण्याय च प्रपथ्याय च नमः किꣳशिलाय च क्षयणाय च नमः कपर्दिने च पुलस्तये च नमो गोष्ठ्याय च गृह्याय च नमस्तल्प्याय च गेह्याय च नमः काट्याय च गह्वरेष्ठाय च नमो हृदय्याय च निवेष्प्याय च नमः पाꣳसव्याय च रजस्याय च नमः शुष्क्याय च हरित्याय च नमो लोप्याय चोलप्याय च नम ऊर्व्याय च सूर्म्याय च नमः पर्ण्याय च पर्णशद्याय च नमोऽपगुरमाणाय चाभिघ्नते च नम आख्खिदते च प्रख्खिदते च नमो वः किरिकेभ्यो देवानाꣳ हृदयेभ्यो नमो विक्षीणकेभ्यो नमो विचिन्वत्केभ्यो नम आनिर्हतेभ्यो नम आमीवत्केभ्यः ॥ ९ ॥",
      "transliteration": "nama iriṇyāya ca prapathyāya ca namaḥ kiṃśilāya ca kṣayaṇāya ca namaḥ kapardine ca pulastaye ca namo goṣṭhyāya ca gṛhyāya ca namastalpyāya ca gehyāya ca namaḥ kāṭyāya ca gahvareṣṭhāya ca namo hṛdayyāya ca niveṣpyāya ca namaḥ pāṃsavyāya ca rajasyāya ca namaḥ śuṣkyāya ca harityāya ca namo lopyāya colapyāya ca nama ūrvyāya ca sūrmyāya ca namaḥ parṇyāya ca parṇaśadyāya ca namo'paguramāṇāya cābhighnate ca nama ākhkhidate ca prakhkhidate ca namo vaḥ kirikebhyo devānāṃ hṛdayebhyo namo vikṣīṇakebhyo namo vicinvatkebhyo nama ānirhatebhyo nama āmīvatkebhyaḥ || 9 ||",
      "theme": "Salutations to Rudra in remote places and hearts of gods",
      "meaning": "This anuvaka salutes Rudra pervading desolate lands and highways, small stones and dwelling places, cowsheds and homes, beds and chambers, deep caves and the human heart. He resides in dust and pollen, in dry places and greenery, in leaves and fallen foliage, in those who threaten and strike. The salutations culminate in homage to Rudra as the very hearts of the gods (devanam hridayebhyah), acknowledging that He is the inner essence of all divinity itself.",
      "youtubeTime": 536
    },
    {
      "number": 10,
      "section": "namakam",
      "sanskrit": "द्रापे अन्धसस्पते दरिद्रन्नीललोहित । एषां पुरुषाणामेषां पशूनां मा भेर्माऽरो मो एषां किञ्चनाममत् ॥\nया ते रुद्र शिवा तनूः शिवा विश्वाहभेषजी । शिवा रुद्रस्य भेषजी तया नो मृड जीवसे ॥\nइमाꣳ रुद्राय तवसे कपर्दिने क्षयद्वीराय प्रभरामहे मतिम् । यथा नः शमसद्द्विपदे चतुष्पदे विश्वं पुष्टं ग्रामे अस्मिन्ननातुरम् ॥\nमृडा नो रुद्रोत नो मयस्कृधि क्षयद्वीराय नमसा विधेम ते । यच्छं च योश्च मनुरायजे पिता तदश्याम तव रुद्र प्रणीतौ ॥\nमा नो महान्तमुत मा नो अर्भकं मा न उक्षन्तमुत मा न उक्षितम् । मा नो वधीः पितरं मोत मातरं प्रिया मा नस्तनुवो रुद्र रीरिषः ॥\nमा नस्तोके तनये मा न आयुषि मा नो गोषु मा नो अश्वेषु रीरिषः । वीरान्मा नो रुद्र भामितोऽवधीर्हविष्मन्तो नमसा विधेम ते ॥\nआरात्ते गोघ्न उत पूरुषघ्ने क्षयद्वीराय सुम्नमस्मे ते अस्तु । रक्षा च नो अधि च देव ब्रूह्यथा च नः शर्म यच्छ द्विबर्हाः ॥\nस्तुहि श्रुतं गर्तसदं युवानं मृगन्न भीममुपहत्नुमुग्रम् । मृडा जरित्रे रुद्र स्तवानो अन्यन्ते अस्मन्निवपन्तु सेनाः ॥\nपरिणो रुद्रस्य हेतिर्वृणक्तु परि त्वेषस्य दुर्मतिरघायोः । अव स्थिरा मघवद्भ्यस्तनुष्व मीढ्वस्तोकाय तनयाय मृडय ॥\nमीढुष्टम शिवतम शिवो नः सुमना भव । परमे वृक्ष आयुधन्निधाय कृत्तिं वसान आचर पिनाकं बिभ्रदागहि ॥\nविकिरिद विलोहित नमस्ते अस्तु भगवः । यास्ते सहस्रꣳ हेतयोऽन्यमस्मन्निवपन्तु ताः ॥\nसहस्राणि सहस्रधा बाहुवोस्तव हेतयः । तासामीशानो भगवः पराचीना मुखा कृधि ॥ १० ॥",
      "transliteration": "drāpe andhasaspate daridrannīlalohita | eṣāṃ puruṣāṇāmeṣāṃ paśūnāṃ mā bhermā'ro mo eṣāṃ kiñcanāmamat ||\nyā te rudra śivā tanūḥ śivā viśvāhabheṣajī | śivā rudrasya bheṣajī tayā no mṛḍa jīvase ||\nimāṃ rudrāya tavase kapardine kṣayadvīrāya prabharāmahe matim | yathā naḥ śamasaddvipade catuṣpade viśvaṃ puṣṭaṃ grāme asminnanāturam ||\nmṛḍā no rudrota no mayaskṛdhi kṣayadvīrāya namasā vidhema te | yacchaṃ ca yośca manurāyaje pitā tadaśyāma tava rudra praṇītau ||\nmā no mahāntamuta mā no arbhakaṃ mā na ukṣantamuta mā na ukṣitam | mā no vadhīḥ pitaraṃ mota mātaraṃ priyā mā nastanuvo rudra rīriṣaḥ ||\nmā nastoke tanaye mā na āyuṣi mā no goṣu mā no aśveṣu rīriṣaḥ | vīrānmā no rudra bhāmito'vadhīrhaviṣmanto namasā vidhema te ||\nārātte goghna uta pūruṣaghne kṣayadvīrāya sumnamasme te astu | rakṣā ca no adhi ca deva brūhyathā ca naḥ śarma yaccha dvibarhāḥ ||\nstuhi śrutaṃ gartasadaṃ yuvānaṃ mṛganna bhīmamupahatnumugram | mṛḍā jaritre rudra stavāno anyante asmannivapantu senāḥ ||\npariṇo rudrasya hetirvṛṇaktu pari tveṣasya durmatiraghāyoḥ | ava sthirā maghavadbhyastanuṣva mīḍhvastokāya tanayāya mṛḍaya ||\nmīḍhuṣṭama śivatama śivo naḥ sumanā bhava | parame vṛkṣa āyudhannidhāya kṛttiṃ vasāna ācara pinākaṃ bibhradāgahi ||\nvikirida vilohita namaste astu bhagavaḥ | yāste sahasraṃ hetayo'nyamasmannivapantu tāḥ ||\nsahasrāṇi sahasradhā bāhuvostava hetayaḥ | tāsāmīśāno bhagavaḥ parācīnā mukhā kṛdhi || 10 ||",
      "theme": "Prayer for Rudra's auspicious form and protection",
      "meaning": "This anuvaka is a deeply personal petition to Rudra - praying that He harm none of our people or animals, that His auspicious form which is the universal healer (vishvabheshaji) grant us life. The devotee begs Rudra not to slay their elders, children, cows, horses, or beloved ones. It requests Rudra to hang His weapons on a distant tree, wear His tiger-skin peacefully, and come bearing His Pinaka bow. All His thousand weapons should be turned away from us toward others.",
      "youtubeTime": 588
    },
    {
      "number": 11,
      "section": "namakam",
      "sanskrit": "सहस्राणि सहस्रशो ये रुद्रा अधि भूम्याम् । तेषाꣳ सहस्रयोजनेऽवधन्वानि तन्मसि ॥\nअस्मिन्महत्यर्णवेऽन्तरिक्षे भवा अधि ॥\nनीलग्रीवाः शितिकण्ठाः शर्वा अधः क्षमाचराः ॥\nनीलग्रीवाः शितिकण्ठा दिवꣳ रुद्रा उपश्रिताः ॥\nये वृक्षेषु सस्पिञ्जरा नीलग्रीवा विलोहिताः ॥\nये भूतानामधिपतयो विशिखासः कपर्दिनः ॥\nये अन्नेषु विविध्यन्ति पात्रेषु पिबतो जनान् ॥\nये पथां पथिरक्षय ऐलबृदा यव्युधः ॥\nये तीर्थानि प्रचरन्ति सृकावन्तो निषङ्गिणः ॥\nय एतावन्तश्च भूयाꣳसश्च दिशो रुद्रा वितस्थिरे । तेषाꣳ सहस्रयोजनेऽवधन्वानि तन्मसि ॥\nनमो रुद्रेभ्यो ये पृथिव्यां येऽन्तरिक्षे ये दिवि येषामन्नं वातो वर्षमिषवस्तेभ्यो दश प्राचीर्दश दक्षिणा दश प्रतीचीर्दशोदीचीर्दशोर्ध्वास्तेभ्यो नमस्ते नो मृडयन्तु ते यं द्विष्मो यश्च नो द्वेष्टि तं वो जम्भे दधामि ॥\nत्र्यम्बकं यजामहे सुगन्धिं पुष्टिवर्धनम् । उर्वारुकमिव बन्धनान्मृत्योर्मुक्षीय माऽमृतात् ॥\nयो रुद्रो अग्नौ यो अप्सु य ओषधीषु यो रुद्रो विश्वा भुवनाऽऽविवेश तस्मै रुद्राय नमो अस्तु ॥\nतमु ष्टुहि यः स्विषुः सुधन्वा यो विश्वस्य क्षयति भेषजस्य । यक्ष्वामहे सौमनसाय रुद्रं नमोभिर्देवमसुरं दुवस्य ॥\nअयं मे हस्तो भगवानयं मे भगवत्तरः । अयं मे विश्वभेषजोऽयꣳ शिवाभिमर्शनः ॥\nये ते सहस्रमयुतं पाशा मृत्यो मर्त्याय हन्तवे । तान् यज्ञस्य मायया सर्वानव यजामहे । मृत्यवे स्वाहा मृत्यवे स्वाहा ॥\nॐ नमो भगवते रुद्राय विष्णवे मृत्युर्मे पाहि ॥\nप्राणानां ग्रन्थिरसि रुद्रो मा विशान्तकः । तेनान्नेनाप्यायस्व ॥\nॐ नमो भगवते रुद्राय ॥\nॐ शान्तिः शान्तिः शान्तिः ॥ ११ ॥",
      "transliteration": "sahasrāṇi sahasraśo ye rudrā adhi bhūmyām | teṣāṃ sahasrayojane'vadhanvāni tanmasi ||\nasminmahatyarṇave'ntarikṣe bhavā adhi ||\nnīlagrīvāḥ śitikaṇṭhāḥ śarvā adhaḥ kṣamācarāḥ ||\nnīlagrīvāḥ śitikaṇṭhā divaṃ rudrā upaśritāḥ ||\nye vṛkṣeṣu saspiñjarā nīlagrīvā vilohitāḥ ||\nye bhūtānāmadhipatayo viśikhāsaḥ kapardinaḥ ||\nye anneṣu vividhyanti pātreṣu pibato janān ||\nye pathāṃ pathirakṣaya ailabṛdā yavyudhaḥ ||\nye tīrthāni pracaranti sṛkāvanto niṣaṅgiṇaḥ ||\nya etāvantaśca bhūyāṃsaśca diśo rudrā vitasthire | teṣāṃ sahasrayojane'vadhanvāni tanmasi ||\nnamo rudrebhyo ye pṛthivyāṃ ye'ntarikṣe ye divi yeṣāmannaṃ vāto varṣamiṣavastebhyo daśa prācīrdaśa dakṣiṇā daśa pratīcīrdaśodīcīrdaśordhvāstebhyo namaste no mṛḍayantu te yaṃ dviṣmo yaśca no dveṣṭi taṃ vo jambhe dadhāmi ||\ntryambakaṃ yajāmahe sugandhiṃ puṣṭivardhanam | urvārukamiva bandhanānmṛtyormukṣīya mā'mṛtāt ||\nyo rudro agnau yo apsu ya oṣadhīṣu yo rudro viśvā bhuvanā''viveśa tasmai rudrāya namo astu ||\ntamu ṣṭuhi yaḥ sviṣuḥ sudhanvā yo viśvasya kṣayati bheṣajasya | yakṣvāmahe saumanasāya rudraṃ namobhirdevamasuraṃ duvasya ||\nayaṃ me hasto bhagavānayaṃ me bhagavattaraḥ | ayaṃ me viśvabheṣajo'yaṃ śivābhimarśanaḥ ||\nye te sahasramayutaṃ pāśā mṛtyo martyāya hantave | tān yajñasya māyayā sarvānava yajāmahe | mṛtyave svāhā mṛtyave svāhā ||\noṃ namo bhagavate rudrāya viṣṇave mṛtyurme pāhi ||\nprāṇānāṃ granthirasi rudro mā viśāntakaḥ | tenānnenāpyāyasva ||\noṃ namo bhagavate rudrāya ||\noṃ śāntiḥ śāntiḥ śāntiḥ || 11 ||",
      "theme": "Thousand Rudras, Mrityunjaya, and final peace",
      "meaning": "The concluding anuvaka acknowledges the thousands of Rudras spread across earth, sky, heavens, trees, food, waters, and pathways, requesting them to unstring their bows a thousand yojanas away. It contains the legendary Maha Mrityunjaya mantra 'tryambakam yajamahe' - worshipping the three-eyed fragrant one who nourishes all, praying to be freed from death like a ripe cucumber from its vine, but not from immortality. It ends with surrender to Rudra dwelling in fire, water, herbs, and all worlds, culminating in the triple invocation of peace: Om Shanti Shanti Shanti.",
      "youtubeTime": 738
    }
  ],
  "chamakam": [
    {
      "number": 1,
      "section": "chamakam",
      "sanskrit": "ॐ अग्नाविष्णू सजोषसेमा वर्धन्तु वां गिरः । द्युम्नैर्वाजेभिरागतम् ॥\nवाजश्च मे प्रसवश्च मे प्रयतिश्च मे प्रसितिश्च मे धीतिश्च मे क्रतुश्च मे स्वरश्च मे श्लोकश्च मे श्रावश्च मे श्रुतिश्च मे ज्योतिश्च मे सुवश्च मे प्राणश्च मेऽपानश्च मे व्यानश्च मेऽसुश्च मे चित्तं च म आधीतं च मे वाक्च मे मनश्च मे चक्षुश्च मे श्रोत्रं च मे दक्षश्च मे बलं च म ओजश्च मे सहश्च म आयुश्च मे जरा च म आत्मा च मे तनूश्च मे शर्म च मे वर्म च मेऽङ्गानि च मेऽस्थानि च मे परूꣳषि च मे शरीराणि च मे ॥ १ ॥",
      "transliteration": "oṃ agnāviṣṇū sajoṣasemā vardhantu vāṃ giraḥ | dyumnairvājebhirāgatam ||\nvājaśca me prasavaśca me prayatiśca me prasitiśca me dhītiśca me kratuśca me svaraśca me ślokaśca me śrāvaśca me śrutiśca me jyotiśca me suvaśca me prāṇaśca me'pānaśca me vyānaśca me'suśca me cittaṃ ca ma ādhītaṃ ca me vākca me manaśca me cakṣuśca me śrotraṃ ca me dakṣaśca me balaṃ ca ma ojaśca me sahaśca ma āyuśca me jarā ca ma ātmā ca me tanūśca me śarma ca me varma ca me'ṅgāni ca me'sthāni ca me parūṃṣi ca me śarīrāṇi ca me || 1 ||",
      "theme": "Invocation of Agni-Vishnu for vital faculties",
      "meaning": "The opening anuvaka invokes Agni and Vishnu together, asking that our hymns nourish them and that they come with brilliance and strength. The devotee then asks for a cascade of essential qualities: food, progress, attention, concentration, sacred knowledge, resolve, melody and verse, fame and hearing, light and heaven, all five pranas (vital airs), mind and consciousness, speech and senses, dexterity, strength, vigor, life-span, a protected body with all its limbs and bones intact.",
      "youtubeTime": 907
    },
    {
      "number": 2,
      "section": "chamakam",
      "sanskrit": "ज्यैष्ठ्यं च म आधिपत्यं च मे मन्युश्च मे भामश्च मेऽमश्च मेऽम्भश्च मे जेमा च मे महिमा च मे वरिमा च मे प्रथिमा च मे वर्ष्मा च मे द्राघुया च मे वृद्धं च मे वृद्धिश्च मे सत्यं च मे श्रद्धा च मे जगच्च मे धनं च मे वशश्च मे त्विषिश्च मे क्रीडा च मे मोदश्च मे जातं च मे जनिष्यमाणं च मे सूक्तं च मे सुकृतं च मे वित्तं च मे वेद्यं च मे भूतं च मे भविष्यच्च मे सुगं च मे सुपथं च म ऋद्धं च म ऋद्धिश्च मे क्लृप्तं च मे क्लृप्तिश्च मे मतिश्च मे सुमतिश्च मे ॥ २ ॥",
      "transliteration": "jyaiṣṭhyaṃ ca ma ādhipatyaṃ ca me manyuśca me bhāmaśca me'maśca me'mbhaśca me jemā ca me mahimā ca me varimā ca me prathimā ca me varṣmā ca me drāghuyā ca me vṛddhaṃ ca me vṛddhiśca me satyaṃ ca me śraddhā ca me jagacca me dhanaṃ ca me vaśaśca me tviṣiśca me krīḍā ca me modaśca me jātaṃ ca me janiṣyamāṇaṃ ca me sūktaṃ ca me sukṛtaṃ ca me vittaṃ ca me vedyaṃ ca me bhūtaṃ ca me bhaviṣyacca me sugaṃ ca me supathaṃ ca ma ṛddhaṃ ca ma ṛddhiśca me klṛptaṃ ca me klṛptiśca me matiśca me sumatiśca me || 2 ||",
      "theme": "Prayer for preeminence, greatness, and success",
      "meaning": "This anuvaka requests superiority and lordship, righteous indignation and splendor, powers of strength and water, conquest and greatness, breadth and expansion, height and length, fullness and growth. It asks for truth and faith, the world and wealth, control and brilliance, play and joy, that which is born and is yet to be born. The seeker prays for well-recited hymns, good deeds, wealth-gaining and knowledge, past and future, easy paths and prosperity, proper order and intelligent thought.",
      "youtubeTime": 950
    },
    {
      "number": 3,
      "section": "chamakam",
      "sanskrit": "शं च मे मयश्च मे प्रियं च मेऽनुकामश्च मे कामश्च मे सौमनसश्च मे भद्रं च मे श्रेयश्च मे वस्यश्च मे यशश्च मे भगश्च मे द्रविणं च मे यन्ता च मे धर्ता च मे क्षेमश्च मे धृतिश्च मे विश्वं च मे महश्च मे संविच्च मे ज्ञात्रं च मे सूश्च मे प्रसूश्च मे सीरं च मे लयश्च म ऋतं च मेऽमृतं च मेऽयक्ष्मं च मेऽनामयच्च मे जीवातुश्च मे दीर्घायुत्वं च मेऽनमित्रं च मेऽभयं च मे सुगं च मे शयनं च मे सूषा च मे सुदिनं च मे ॥ ३ ॥",
      "transliteration": "śaṃ ca me mayaśca me priyaṃ ca me'nukāmaśca me kāmaśca me saumanasaśca me bhadraṃ ca me śreyaśca me vasyaśca me yaśaśca me bhagaśca me draviṇaṃ ca me yantā ca me dhartā ca me kṣemaśca me dhṛtiśca me viśvaṃ ca me mahaśca me saṃvicca me jñātraṃ ca me sūśca me prasūśca me sīraṃ ca me layaśca ma ṛtaṃ ca me'mṛtaṃ ca me'yakṣmaṃ ca me'nāmayacca me jīvātuśca me dīrghāyutvaṃ ca me'namitraṃ ca me'bhayaṃ ca me sugaṃ ca me śayanaṃ ca me sūṣā ca me sudinaṃ ca me || 3 ||",
      "theme": "Prayer for peace, happiness, and well-being",
      "meaning": "This anuvaka requests peace and happiness, the dear and desired, auspiciousness and welfare, prosperity and fame, fortune and wealth, a guide and a supporter. It asks for well-being and fortitude, the universe and greatness, knowledge and discernment, creative power and dissolution, cosmic order (rita) and immortality, freedom from disease and affliction, vitality and long life, absence of enemies, fearlessness, easy paths, comfortable sleep, beautiful dawns, and pleasant days.",
      "youtubeTime": 992
    },
    {
      "number": 4,
      "section": "chamakam",
      "sanskrit": "ऊर्क्च मे सूनृता च मे पयश्च मे रसश्च मे घृतं च मे मधु च मे सग्धिश्च मे सपीतिश्च मे कृषिश्च मे वृष्टिश्च मे जैत्रं च म औद्भिद्यं च मे रयिश्च मे रायश्च मे पुष्टं च मे पुष्टिश्च मे विभु च मे प्रभु च मे बहु च मे भूयश्च मे पूर्णं च मे पूर्णतरं च मेऽक्षितिश्च मे कूयवाश्च मेऽन्नं च मेऽक्षुच्च मे व्रीहयश्च मे यवाश्च मे माषाश्च मे तिलाश्च मे मुद्गाश्च मे खल्वाश्च मे गोधूमाश्च मे मसुराश्च मे प्रियङ्गवश्च मेऽणवश्च मे श्यामाकाश्च मे नीवाराश्च मे ॥ ४ ॥",
      "transliteration": "ūrkca me sūnṛtā ca me payaśca me rasaśca me ghṛtaṃ ca me madhu ca me sagdhiśca me sapītiśca me kṛṣiśca me vṛṣṭiśca me jaitraṃ ca ma audbhidyaṃ ca me rayiśca me rāyaśca me puṣṭaṃ ca me puṣṭiśca me vibhu ca me prabhu ca me bahu ca me bhūyaśca me pūrṇaṃ ca me pūrṇataraṃ ca me'kṣitiśca me kūyavāśca me'nnaṃ ca me'kṣucca me vrīhayaśca me yavāśca me māṣāśca me tilāśca me mudgāśca me khalvāśca me godhūmāśca me masurāśca me priyaṅgavaśca me'ṇavaśca me śyāmākāśca me nīvārāśca me || 4 ||",
      "theme": "Prayer for food, nourishment, and grains",
      "meaning": "This anuvaka requests nourishment and pleasant speech, milk and sap, clarified butter and honey, the joy of eating together and drinking together, agriculture and rainfall, victory and spontaneous growth, wealth and treasures, fullness and abundance. It specifically enumerates the grains: rice and barley, black gram and sesame, green gram and pulses, wheat and lentils, priyangu and anu (tiny grains), shyamaka and nivara (wild rice) - a complete inventory of food crops for prosperity.",
      "youtubeTime": 1030
    },
    {
      "number": 5,
      "section": "chamakam",
      "sanskrit": "अश्मा च मे मृत्तिका च मे गिरयश्च मे पर्वताश्च मे सिकताश्च मे वनस्पतयश्च मे हिरण्यं च मेऽयश्च मे सीसं च मे त्रपुश्च मे श्यामं च मे लोहं च मेऽग्निश्च म आपश्च मे वीरुधश्च म ओषधयश्च मे कृष्टपच्यं च मेऽकृष्टपच्यं च मे ग्राम्याश्च मे पशव आरण्याश्च यज्ञेन कल्पन्तां वित्तं च मे वित्तिश्च मे भूतं च मे भूतिश्च मे वसु च मे वसतिश्च मे कर्म च मे शक्तिश्च मेऽर्थश्च म एमश्च म इतिश्च मे गतिश्च मे ॥ ५ ॥",
      "transliteration": "aśmā ca me mṛttikā ca me girayaśca me parvatāśca me sikatāśca me vanaspatayaśca me hiraṇyaṃ ca me'yaśca me sīsaṃ ca me trapuśca me śyāmaṃ ca me lohaṃ ca me'gniśca ma āpaśca me vīrudhaśca ma oṣadhayaśca me kṛṣṭapacyaṃ ca me'kṛṣṭapacyaṃ ca me grāmyāśca me paśava āraṇyāśca yajñena kalpantāṃ vittaṃ ca me vittiśca me bhūtaṃ ca me bhūtiśca me vasu ca me vasatiśca me karma ca me śaktiśca me'rthaśca ma emaśca ma itiśca me gatiśca me || 5 ||",
      "theme": "Prayer for materials, elements, and cattle",
      "meaning": "This anuvaka requests stone and clay, hills and mountains, sand and great trees, gold and iron, lead and tin, copper and steel. It asks that fire and water, creepers and medicinal herbs, cultivated crops and wild produce, village cattle and forest animals all prosper through yajna (sacrifice). The seeker prays for wealth and wealth-acquisition, being and prosperity, goods and dwelling, work and power, purpose and progress - the complete material foundation for life.",
      "youtubeTime": 1074
    },
    {
      "number": 6,
      "section": "chamakam",
      "sanskrit": "अग्निश्च म इन्द्रश्च मे सोमश्च म इन्द्रश्च मे सविता च म इन्द्रश्च मे सरस्वती च म इन्द्रश्च मे पूषा च म इन्द्रश्च मे बृहस्पतिश्च म इन्द्रश्च मे मित्रश्च म इन्द्रश्च मे वरुणश्च म इन्द्रश्च मे त्वष्टा च म इन्द्रश्च मे धाता च म इन्द्रश्च मे विष्णुश्च म इन्द्रश्च मेऽश्विनौ च म इन्द्रश्च मे मरुतश्च म इन्द्रश्च मे विश्वे च मे देवा इन्द्रश्च मे पृथिवी च म इन्द्रश्च मेऽन्तरिक्षं च म इन्द्रश्च मे द्यौश्च म इन्द्रश्च मे दिशश्च म इन्द्रश्च मे मूर्धा च म इन्द्रश्च मे प्रजापतिश्च म इन्द्रश्च मे ॥ ६ ॥",
      "transliteration": "agniśca ma indraśca me somaśca ma indraśca me savitā ca ma indraśca me sarasvatī ca ma indraśca me pūṣā ca ma indraśca me bṛhaspatiśca ma indraśca me mitraśca ma indraśca me varuṇaśca ma indraśca me tvaṣṭā ca ma indraśca me dhātā ca ma indraśca me viṣṇuśca ma indraśca me'śvinau ca ma indraśca me marutaśca ma indraśca me viśve ca me devā indraśca me pṛthivī ca ma indraśca me'ntarikṣaṃ ca ma indraśca me dyauśca ma indraśca me diśaśca ma indraśca me mūrdhā ca ma indraśca me prajāpatiśca ma indraśca me || 6 ||",
      "theme": "Prayer for all deities paired with Indra",
      "meaning": "This anuvaka invokes a pantheon of Vedic deities, each paired with Indra - Agni and Indra, Soma and Indra, Savitr and Indra, Sarasvati and Indra, Pushan and Indra, Brihaspati, Mitra, Varuna, Tvashta, Dhata, Vishnu, the Ashwins, the Maruts, all the Vishvedevas, paired with Indra. It further asks that earth, mid-space, heavens, directions, zenith, and Prajapati all be granted alongside Indra - the totality of cosmic powers protected by the king of gods.",
      "youtubeTime": 1109
    },
    {
      "number": 7,
      "section": "chamakam",
      "sanskrit": "अꣳशुश्च मे रश्मिश्च मेऽदाभ्यश्च मेऽधिपतिश्च म उपाꣳशुश्च मेऽन्तर्यामश्च म ऐन्द्रवायवश्च मे मैत्रावरुणश्च म आश्विनश्च मे प्रतिप्रस्थानश्च मे शुक्रश्च मे मन्थी च म आग्रयणश्च मे वैश्वदेवश्च मे ध्रुवश्च मे वैश्वानरश्च म ऋतुग्रहाश्च मेऽतिग्राह्याश्च म ऐन्द्राग्नश्च मे वैश्वदेवश्च मे मरुत्वतीयाश्च मे माहेन्द्रश्च म आदित्यश्च मे सावित्रश्च मे सारस्वतश्च मे पौष्णश्च मे पात्नीवतश्च मे हारियोजनश्च मे ॥ ७ ॥",
      "transliteration": "aṃśuśca me raśmiśca me'dābhyaśca me'dhipatiśca ma upāṃśuśca me'ntaryāmaśca ma aindravāyavaśca me maitrāvaruṇaśca ma āśvinaśca me pratiprasthānaśca me śukraśca me manthī ca ma āgrayaṇaśca me vaiśvadevaśca me dhruvaśca me vaiśvānaraśca ma ṛtugrahāśca me'tigrāhyāśca ma aindrāgnaśca me vaiśvadevaśca me marutvatīyāśca me māhendraśca ma ādityaśca me sāvitraśca me sārasvataśca me pauṣṇaśca me pātnīvataśca me hāriyojanaśca me || 7 ||",
      "theme": "Prayer for Soma cups and ritual offerings",
      "meaning": "This anuvaka enumerates the technical components of Soma sacrifice - Amshu and Rashmi (rays/juice portions), Adabhya and Adhipati graha (cups), Upamshu and Antaryama, the Aindravayava, Maitravaruna, and Ashvina cups, Pratiprasthana and Shukra, Manthi and Agrayana. It asks for Vaishvadeva, Dhruva, Vaishvanara cups, the seasonal Ritugrahas, the Atigrahyas, and the graha offerings to Indra-Agni, Vishvedevas, Marutvatiya, Mahendra, Aditya, Savitr, Sarasvati, Pushan, the consort-goddesses, and Hariyojana - every ritual vessel for completeness.",
      "youtubeTime": 1149
    },
    {
      "number": 8,
      "section": "chamakam",
      "sanskrit": "इध्मश्च मे बर्हिश्च मे वेदिश्च मे दिष्णियाश्च मे स्रुचश्च मे चमसाश्च मे ग्रावाणश्च मे स्वरवश्च म उपरवाश्च मेऽधिषवणे च मे द्रोणकलशश्च मे वायव्यानि च मे पूतभृच्च म आधवनीयश्च म आग्नीध्रं च मे हविर्धानं च मे गृहाश्च मे सदश्च मे पुरोडाशाश्च मे पचताश्च मेऽवभृथश्च मे स्वगाकारश्च मे ॥ ८ ॥",
      "transliteration": "idhmaśca me barhiśca me vediśca me diṣṇiyāśca me srucaśca me camasāśca me grāvāṇaśca me svaravaśca ma uparavāśca me'dhiṣavaṇe ca me droṇakalaśaśca me vāyavyāni ca me pūtabhṛcca ma ādhavanīyaśca ma āgnīdhraṃ ca me havirdhānaṃ ca me gṛhāśca me sadaśca me puroḍāśāśca me pacatāśca me'vabhṛthaśca me svagākāraśca me || 8 ||",
      "theme": "Prayer for sacrificial implements and ritual structures",
      "meaning": "This anuvaka requests the physical components of the Vedic yajna - firewood and sacred grass, the altar and subsidiary fire-mounds, ladles and cups, pressing stones and wooden posts, sound-posts and pressing boards, the drona (trough) and the vayavya cups. It asks for the purifying vessel, the pouring cup, the Agnidhra fire, the Havirdhana cart, the sacrificial huts and Sadas hall, the purodasha cakes, the cooked offerings, the final avabhritha bath, and the Svagakara invocation - every element of ritual architecture.",
      "youtubeTime": 1180
    },
    {
      "number": 9,
      "section": "chamakam",
      "sanskrit": "अग्निश्च मे घर्मश्च मेऽर्कश्च मे सूर्यश्च मे प्राणश्च मेऽश्वमेधश्च मे पृथिवी च मेऽदितिश्च मे दितिश्च मे द्यौश्च मे शक्वरीरङ्गुलयो दिशश्च मे यज्ञेन कल्पन्तामृक्च मे साम च मे स्तोमश्च मे यजुश्च मे दीक्षा च मे तपश्च म ऋतुश्च मे व्रतं च मेऽहोरात्रयोर्वृष्ट्या बृहद्रथन्तरे च मे यज्ञेन कल्पेताम् ॥ ९ ॥",
      "transliteration": "agniśca me gharmaśca me'rkaśca me sūryaśca me prāṇaśca me'śvamedhaśca me pṛthivī ca me'ditiśca me ditiśca me dyauśca me śakvarīraṅgulayo diśaśca me yajñena kalpantāmṛkca me sāma ca me stomaśca me yajuśca me dīkṣā ca me tapaśca ma ṛtuśca me vrataṃ ca me'horātrayorvṛṣṭyā bṛhadrathantare ca me yajñena kalpetām || 9 ||",
      "theme": "Prayer for cosmic forces and Vedic knowledge",
      "meaning": "This anuvaka requests fire and heat, the sun-ray and the sun itself, life-breath and the great Ashvamedha sacrifice, earth and Aditi and Diti, heaven and the fingers like Shakkaris, and the directions - all harmonized through yajna. It asks that the Rig, Sama, Stoma, and Yajus Vedic chants, initiation (diksha) and austerity (tapas), seasons and sacred vows, day and night's rainfall, and the great Brihad and Rathantara Samans all be fulfilled through sacrifice.",
      "youtubeTime": 1216
    },
    {
      "number": 10,
      "section": "chamakam",
      "sanskrit": "गर्भाश्च मे वत्साश्च मे त्र्यविश्च मे त्र्यवी च मे दित्यवाट् च मे दित्यौही च मे पञ्चाविश्च मे पञ्चावी च मे त्रिवत्सश्च मे त्रिवत्सा च मे तुर्यवाट् च मे तुर्यौही च मे पष्ठवाट् च मे पष्ठौही च म उक्षा च मे वशा च म ऋषभश्च मे वेहच्च मेऽनड्वाञ्च मे धेनुश्च म आयुर्यज्ञेन कल्पतां प्राणो यज्ञेन कल्पतामपानो यज्ञेन कल्पतां व्यानो यज्ञेन कल्पतां चक्षुर्यज्ञेन कल्पताꣳ श्रोत्रं यज्ञेन कल्पतां मनो यज्ञेन कल्पतां वाग्यज्ञेन कल्पतामात्मा यज्ञेन कल्पतां यज्ञो यज्ञेन कल्पताम् ॥ १० ॥",
      "transliteration": "garbhāśca me vatsāśca me tryaviśca me tryavī ca me dityavāṭ ca me dityauhī ca me pañcāviśca me pañcāvī ca me trivatsaśca me trivatsā ca me turyavāṭ ca me turyauhī ca me paṣṭhavāṭ ca me paṣṭhauhī ca ma ukṣā ca me vaśā ca ma ṛṣabhaśca me vehacca me'naḍvāñca me dhenuśca ma āyuryajñena kalpatāṃ prāṇo yajñena kalpatāmapāno yajñena kalpatāṃ vyāno yajñena kalpatāṃ cakṣuryajñena kalpatāṃ śrotraṃ yajñena kalpatāṃ mano yajñena kalpatāṃ vāgyajñena kalpatāmātmā yajñena kalpatāṃ yajño yajñena kalpatām || 10 ||",
      "theme": "Prayer for livestock and harmonizing life through yajna",
      "meaning": "This anuvaka requests pregnant cows and calves, yearling bulls and heifers, two-year-olds and three-year-olds, four-year-olds and six-year-olds, bulls and barren cows, the mighty bull, the sterile cow, the draft ox and the milch cow. Then in a crescendo, it prays that life-span, prana, apana, vyana, sight, hearing, mind, speech, the Self, and the yajna itself all be perfectly harmonized through sacrifice - the complete alignment of body, senses, and soul through sacred ritual.",
      "youtubeTime": 1245
    },
    {
      "number": 11,
      "section": "chamakam",
      "sanskrit": "एका च मे तिस्रश्च मे पञ्च च मे सप्त च मे नव च म एकादश च मे त्रयोदश च मे पञ्चदश च मे सप्तदश च मे नवदश च म एकविꣳशतिश्च मे त्रयोविꣳशतिश्च मे पञ्चविꣳशतिश्च मे सप्तविꣳशतिश्च मे नवविꣳशतिश्च म एकत्रिꣳशच्च मे त्रयस्त्रिꣳशच्च मे चतस्रश्च मेऽष्टौ च मे द्वादश च मे षोडश च मे विꣳशतिश्च मे चतुर्विꣳशतिश्च मेऽष्टाविꣳशतिश्च मे द्वात्रिꣳशच्च मे षट्त्रिꣳशच्च मे चत्वरिꣳशच्च मे चतुश्चत्वारिꣳशच्च मेऽष्टाचत्वारिꣳशच्च मे वाजश्च प्रसवश्चापिजश्च क्रतुश्च सुवश्च मूर्धा च व्यश्नियश्चान्त्यायनश्चान्त्यश्च भौवनश्च भुवनश्चाधिपतिश्च ॥\nॐ इडा देवहूर्मनुर्यज्ञनीर्बृहस्पतिरुक्थामदानि शꣳसिषद्विश्वेदेवाः सूक्तवाचः पृथिवीमातर्मा मा हिꣳसीर्मधु मनिष्ये मधु जनिष्ये मधु वक्ष्यामि मधु वदिष्यामि मधुमतीं देवेभ्यो वाचमुद्यासꣳ शुश्रूषेण्यां मनुष्येभ्यस्तं मा देवा अवन्तु शोभायै पितरोऽनुमदन्तु ॥\nॐ शान्तिः शान्तिः शान्तिः ॥ ११ ॥",
      "transliteration": "ekā ca me tisraśca me pañca ca me sapta ca me nava ca ma ekādaśa ca me trayodaśa ca me pañcadaśa ca me saptadaśa ca me navadaśa ca ma ekaviṃśatiśca me trayoviṃśatiśca me pañcaviṃśatiśca me saptaviṃśatiśca me navaviṃśatiśca ma ekatriṃśacca me trayastriṃśacca me catasraśca me'ṣṭau ca me dvādaśa ca me ṣoḍaśa ca me viṃśatiśca me caturviṃśatiśca me'ṣṭāviṃśatiśca me dvātriṃśacca me ṣaṭtriṃśacca me catvariṃśacca me catuścatvāriṃśacca me'ṣṭācatvāriṃśacca me vājaśca prasavaścāpijaśca kratuśca suvaśca mūrdhā ca vyaśniyaścāntyāyanaścāntyaśca bhauvanaśca bhuvanaścādhipatiśca ||\noṃ iḍā devahūrmanuryajñanīrbṛhaspatirukthāmadāni śaṃsiṣadviśvedevāḥ sūktavācaḥ pṛthivīmātarmā mā hiṃsīrmadhu maniṣye madhu janiṣye madhu vakṣyāmi madhu vadiṣyāmi madhumatīṃ devebhyo vācamudyāsaṃ śuśrūṣeṇyāṃ manuṣyebhyastaṃ mā devā avantu śobhāyai pitaro'numadantu ||\noṃ śāntiḥ śāntiḥ śāntiḥ || 11 ||",
      "theme": "Odd and even numbers series with final benediction",
      "meaning": "The concluding anuvaka contains the famous numerical series - odd numbers (1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33) and even numbers (4, 8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48) - representing completeness in every dimension. It ends with the Idadevahuh invocation, the Madhuvidya prayer (may I think, produce, speak, and declare sweetness), and the triple peace invocation, asking the mother earth not to harm, and that the gods protect and the ancestors rejoice.",
      "youtubeTime": 1290
    }
  ],
  "meta": {
    "title": "Sri Rudram",
    "subtitle": "Rudra Prashna / Shatarudriya",
    "source": "Krishna Yajurveda, Taittiriya Samhita, Kanda 4",
    "youtubeVideoId": "L4yT_UpfJdw",
    "totalAnuvakas": 22
  }
};
